<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>dotnet-FlexAgent.Worker-6ca7551c-c224-45e6-8aaa-057c208cf4ea</UserSecretsId>
    <RootNamespace>FlexAgent.Worker</RootNamespace>
    <AssemblyName>FlexAgent.Worker</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\IdentityAccess\FlexAgent.IdentityAccess\FlexAgent.IdentityAccess.csproj" />
    <ProjectReference Include="..\..\Modules\Sessions\FlexAgent.Sessions\FlexAgent.Sessions.csproj" />
    <ProjectReference Include="..\..\Modules\Sessions\FlexAgent.Sessions.Infrastructure\FlexAgent.Sessions.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Sessions\FlexAgent.Sessions.OpenAi\FlexAgent.Sessions.OpenAi.csproj" />
  </ItemGroup>
</Project>
