<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>FlexAgent.Postgres</RootNamespace>
    <AssemblyName>FlexAgent.Postgres</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FlexAgent.Postgres.Integration.Tests" />
  </ItemGroup>

</Project>
