<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>FlexAgent.Api</RootNamespace>
    <AssemblyName>FlexAgent.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\SyntheticBrowser\FlexAgent.SyntheticBrowser\FlexAgent.SyntheticBrowser.csproj" />
  </ItemGroup>

</Project>
